AGV5:
  amcl:
    ros__parameters:
      use_sim_time: true
      base_frame_id: "AGV5/base_link"
      odom_frame_id: "AGV5/odom"
      global_frame_id: "map"
      robot_model_type: "nav2_amcl::DifferentialMotionModel"
      transform_tolerance: 1.0
      scan_topic: "/AGV5/scan"
      tf_broadcast: true
      set_initial_pose: true
      initial_pose: { x: 23.0, y: 3.0, z: 0.0, yaw: 1.5708 }

  controller_server:
    ros__parameters:
      robot_base_frame: AGV5/base_link
      use_sim_time: true
      controller_frequency: 10.0
      controller_plugins: ["FollowPath"]
      FollowPath:
        plugin: "dwb_core::DWBLocalPlanner"
        # ... your DWB parameters
        critics:
          [
            "RotateToGoal",
            "Oscillation",
            "ObstacleFootprint",
            "GoalAlign",
            "PathAlign",
            "PathDist",
            "GoalDist",
          ]

  bt_navigator:
    ros__parameters:
      use_sim_time: true
      global_frame: "/map"
      robot_base_frame: "AGV5/base_link"
      odom_topic: "/AGV5/odom"
      default_server_timeout: 20
      plugin_lib_names:
        - nav2_compute_path_to_pose_action_bt_node
        - nav2_compute_path_through_poses_action_bt_node
        - nav2_smooth_path_action_bt_node
        - nav2_follow_path_action_bt_node
        - nav2_spin_action_bt_node
        - nav2_wait_action_bt_node
        - nav2_assisted_teleop_action_bt_node
        - nav2_back_up_action_bt_node
        - nav2_drive_on_heading_bt_node
        - nav2_clear_costmap_service_bt_node
        - nav2_is_stuck_condition_bt_node
        - nav2_goal_reached_condition_bt_node
        - nav2_goal_updated_condition_bt_node
        - nav2_globally_updated_goal_condition_bt_node
        - nav2_is_path_valid_condition_bt_node
        - nav2_initial_pose_received_condition_bt_node
        - nav2_reinitialize_global_localization_service_bt_node
        - nav2_rate_controller_bt_node
        - nav2_distance_controller_bt_node
        - nav2_speed_controller_bt_node
        - nav2_truncate_path_action_bt_node
        - nav2_truncate_path_local_action_bt_node
        - nav2_goal_updater_node_bt_node
        - nav2_recovery_node_bt_node
        - nav2_pipeline_sequence_bt_node
        - nav2_round_robin_node_bt_node
        - nav2_transform_available_condition_bt_node
        - nav2_time_expired_condition_bt_node
        - nav2_path_expiring_timer_condition
        - nav2_distance_traveled_condition_bt_node
        - nav2_single_trigger_bt_node
        - nav2_goal_updated_controller_bt_node
        - nav2_is_battery_low_condition_bt_node
        - nav2_navigate_through_poses_action_bt_node
        - nav2_navigate_to_pose_action_bt_node
        - nav2_remove_passed_goals_action_bt_node
        - nav2_planner_selector_bt_node
        - nav2_controller_selector_bt_node
        - nav2_goal_checker_selector_bt_node
        - nav2_controller_cancel_bt_node
        - nav2_path_longer_on_approach_bt_node
        - nav2_wait_cancel_bt_node
        - nav2_spin_cancel_bt_node
        - nav2_back_up_cancel_bt_node
        - nav2_assisted_teleop_cancel_bt_node
        - nav2_drive_on_heading_cancel_bt_node
        - nav2_is_battery_charging_condition_bt_node

  planner_server:
    ros__parameters:
      use_sim_time: true
      planner_plugins: ["GridBased"]
      GridBased:
        plugin: "nav2_navfn_planner/NavfnPlanner"
        tolerance: 0.5
        use_astar: false
        allow_unknown: true

  global_costmap:
    global_costmap:
      ros__parameters:
        use_sim_time: true
        global_frame: "/map"
        robot_base_frame: "AGV5/base_link"
        update_frequency: 5.0
        publish_frequency: 5.0
        width: 10
        height: 10
        resolution: 0.05
        robot_radius: 0.22
        plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
        static_layer:
          plugin: "nav2_costmap_2d::StaticLayer"
          map_subscribe_transient_local: true
        obstacle_layer:
          plugin: "nav2_costmap_2d::ObstacleLayer"
          enabled: true
          observation_sources: "/AGV5/scan"
          scan:
            topic: "/AGV5/scan"
            data_type: "LaserScan"
            marking: true
            clearing: true
        inflation_layer:
          plugin: "nav2_costmap_2d::InflationLayer"
          cost_scaling_factor: 3.0
          inflation_radius: 0.55

  local_costmap:
    local_costmap:
      ros__parameters:
        use_sim_time: true
        global_frame: "AGV5/odom"
        robot_base_frame: "AGV5/base_link"
        update_frequency: 10.0
        publish_frequency: 10.0
        width: 3
        height: 3
        resolution: 0.05
        robot_radius: 0.22
        rolling_window: true
        plugins: ["obstacle_layer", "inflation_layer"]
        obstacle_layer:
          plugin: "nav2_costmap_2d::ObstacleLayer"
          enabled: true
          observation_sources: "/AGV5/scan"
          scan:
            topic: "/AGV5/scan"
            data_type: "LaserScan"
            marking: true
            clearing: true
        inflation_layer:
          plugin: "nav2_costmap_2d::InflationLayer"
          cost_scaling_factor: 3.0
          inflation_radius: 0.55

  lifecycle_manager_navigation:
    ros__parameters:
      autostart: true
      node_names:
        - controller_server
        - smoother_server
        - planner_server
        - behavior_server
        - bt_navigator
        - waypoint_follower
        - velocity_smoother
